name = "iainkirkpatrick-dot-com-workers"
main = "workers/index.ts"
compatibility_date = "2023-11-21"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
[vars]
CLF_AI_GATEWAY_ID = "iainkirkpatrick-ai-gateway"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "SESSION"
id = "1c60017fb48942109a665ce8b60e8023"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# Bind a Queue producer. Use this binding to schedule an arbitrary task that may be processed later by a Queue consumer.
# Docs: https://developers.cloudflare.com/queues/get-started
# [[queues.producers]]
# binding = "MY_QUEUE"
# queue = "my-queue"

# Bind a Queue consumer. Queue Consumers can retrieve tasks scheduled by Producers to act on them.
# Docs: https://developers.cloudflare.com/queues/get-started
# [[queues.consumers]]
# queue = "my-queue"

# Bind another Worker service. Use this binding to call another Worker without network overhead.
# Docs: https://developers.cloudflare.com/workers/platform/services
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# Durable Object migrations.
# Docs: https://developers.cloudflare.com/workers/learning/using-durable-objects#configure-durable-object-classes-with-migrations
# [[migrations]]
# tag = "v1"
# new_classes = ["MyDurableObject"]

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "iainkirkpatrick"

[[d1_databases]]
binding = "DB"
database_name = "database"
database_id = "a27bae71-c16f-43d0-99b3-23e8252d8197"

[env.staging]
name = "iainkirkpatrick-dot-com-workers-staging"

[env.staging.vars]
CLF_AI_GATEWAY_ID = "iainkirkpatrick-ai-gateway"

[env.staging.ai]
binding = "AI"

[[env.staging.vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "iainkirkpatrick-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "iainkirkpatrick-db-staging"
database_id = "cc5e6e72-5ef2-4539-8956-5a6ce447e7b8"

[[env.staging.kv_namespaces]]
binding = "SESSION"
id = "2fa433a6690d449fa19d03b3c1098092"
